version: "3.9"
services:
  kondorudb:
    image: bitnami/postgresql:latest
    container_name: kondoru-postgresql
    networks:
      - kondoru-bridge
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=kondoru_development
    volumes:
      - kondoru_data:/bitnami/postgresql 

  kondoru-backend:
    image: tenoriobn/kondoru-backend:1.0
    container_name: kondoru-backend
    networks:
      - kondoru-bridge
    ports:
      - 8080:8080
    depends_on:
      - kondorudb
    environment:
      - DB_HOST=kondorudb
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_DATABASE=kondoru_development

  kondoru-frontuser:
    image: tenoriobn/kondoru-monorepo:1.0
    container_name: kondoru-frontuser
    networks:
      - kondoru-bridge
    ports:
      - 3000:3000
    depends_on:
      - kondoru-backend
    entrypoint: yarn dev:user

networks:
  kondoru-bridge:
    driver: bridge

volumes:
  kondoru_data: