version: "3.9"
services:
  kondorudb:
    image: bitnami/postgresql:latest
    container_name: kondoru-postgresql
    networks:
      - kondoru-bridge
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=kondoru_development
    volumes:
      - kondoru_data:/bitnami/postgresql 

  kondoru-backend:
    build: ./back-end
    container_name: kondoru-backend
    networks:
      - kondoru-bridge
    ports:
      - 8080:8080
    depends_on:
      - kondorudb
    environment:
      - DB_HOST=kondorudb
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_DATABASE=kondoru_development
    volumes:
      - ./back-end:/back-end:cached
      - /back-end/node_modules

  kondoru-frontuser:
    build: ./mono-repo
    container_name: kondoru-frontuser
    entrypoint: yarn dev:user
    networks:
      - kondoru-bridge
    ports:
      - 3000:3000
    depends_on:
      - kondoru-backend
    volumes:
      - ./mono-repo:/mono-repo:cached
      - /mono-repo/node_modules
    environment:
      - WATCHPACK_POLLING=true

networks:
  kondoru-bridge:
    driver: bridge

volumes:
  kondoru_data: